name: app_olx
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0 #recursos básicos
  firebase_auth: ^4.3.0 #autenticação
  cloud_firestore: ^4.4.5 #banco de dados
  firebase_storage: ^11.1.2 #armazenamento arquivos
  brasil_fields: ^0.0.9 #campos padronizados
  validadores: ^1.0.5
  intl: ^0.17.0 #intl
  cpf_cnpj_validator: 1.0.4 #validador de cpf e cnpj
  image_picker: ^0.8.7+5
  firebase_auth_web: ^5.5.0
  firebase_core_web: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - imagens/logo.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
